# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_settingsDialog(object):
    def setupUi(self, settingsDialog):
        settingsDialog.setObjectName("settingsDialog")
        settingsDialog.resize(418, 371)
        font = QtGui.QFont()
        font.setFamily("Monaco")
        font.setPointSize(11)
        settingsDialog.setFont(font)
        settingsDialog.setToolTip("")
        settingsDialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Germany))
        self.formLayout = QtWidgets.QFormLayout(settingsDialog)
        self.formLayout.setObjectName("formLayout")
        self.masterServerLabel = QtWidgets.QLabel(settingsDialog)
        self.masterServerLabel.setObjectName("masterServerLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.masterServerLabel)
        self.masterServerEdit = QtWidgets.QLineEdit(settingsDialog)
        self.masterServerEdit.setToolTip("")
        self.masterServerEdit.setObjectName("masterServerEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.masterServerEdit)
        self.ddnsKeyFilePathLabel = QtWidgets.QLabel(settingsDialog)
        self.ddnsKeyFilePathLabel.setObjectName("ddnsKeyFilePathLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.ddnsKeyFilePathLabel)
        self.ddnsKeyFilePathEdit = QtWidgets.QLineEdit(settingsDialog)
        self.ddnsKeyFilePathEdit.setObjectName("ddnsKeyFilePathEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ddnsKeyFilePathEdit)
        self.zoneTransferServerLabel = QtWidgets.QLabel(settingsDialog)
        self.zoneTransferServerLabel.setObjectName("zoneTransferServerLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.zoneTransferServerLabel)
        self.zoneTransferServerEdit = QtWidgets.QLineEdit(settingsDialog)
        self.zoneTransferServerEdit.setObjectName("zoneTransferServerEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.zoneTransferServerEdit)
        self.ip4NetworksLabel = QtWidgets.QLabel(settingsDialog)
        self.ip4NetworksLabel.setObjectName("ip4NetworksLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.ip4NetworksLabel)
        self.ip4NetworksListView = QtWidgets.QListView(settingsDialog)
        self.ip4NetworksListView.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ip4NetworksListView.setObjectName("ip4NetworksListView")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.ip4NetworksListView)
        self.ip6NetworksLabel = QtWidgets.QLabel(settingsDialog)
        self.ip6NetworksLabel.setObjectName("ip6NetworksLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.ip6NetworksLabel)
        self.ip4NetworksListView_2 = QtWidgets.QListView(settingsDialog)
        self.ip4NetworksListView_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ip4NetworksListView_2.setObjectName("ip4NetworksListView_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.ip4NetworksListView_2)
        self.ignoredZonesLabel = QtWidgets.QLabel(settingsDialog)
        self.ignoredZonesLabel.setObjectName("ignoredZonesLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.ignoredZonesLabel)
        self.ignoredZonesListView = QtWidgets.QListView(settingsDialog)
        self.ignoredZonesListView.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ignoredZonesListView.setObjectName("ignoredZonesListView")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.ignoredZonesListView)
        self.RevertButton = QtWidgets.QPushButton(settingsDialog)
        self.RevertButton.setObjectName("RevertButton")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.RevertButton)
        self.OKButton = QtWidgets.QPushButton(settingsDialog)
        self.OKButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.OKButton.setObjectName("OKButton")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.OKButton)

        self.retranslateUi(settingsDialog)
        QtCore.QMetaObject.connectSlotsByName(settingsDialog)

    def retranslateUi(self, settingsDialog):
        _translate = QtCore.QCoreApplication.translate
        settingsDialog.setWindowTitle(_translate("settingsDialog", "Dialog"))
        self.masterServerLabel.setText(_translate("settingsDialog", "Master Server"))
        self.ddnsKeyFilePathLabel.setText(_translate("settingsDialog", "ddns Key File"))
        self.zoneTransferServerLabel.setText(_translate("settingsDialog", "Server for Zone Transfer"))
        self.ip4NetworksLabel.setText(_translate("settingsDialog", "IPv4 networks"))
        self.ip6NetworksLabel.setText(_translate("settingsDialog", "IPv6 Networks"))
        self.ignoredZonesLabel.setText(_translate("settingsDialog", "Ignored Zones"))
        self.RevertButton.setText(_translate("settingsDialog", "Revert"))
        self.OKButton.setText(_translate("settingsDialog", "ok"))
