# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(385, 385)
        font = QtGui.QFont()
        font.setFamily("Monaco")
        font.setPointSize(11)
        Dialog.setFont(font)
        Dialog.setToolTip("")
        Dialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Germany))
        self.formLayout = QtWidgets.QFormLayout(Dialog)
        self.formLayout.setObjectName("formLayout")
        self.masterServerLabel = QtWidgets.QLabel(Dialog)
        self.masterServerLabel.setObjectName("masterServerLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.masterServerLabel)
        self.masterServerEdit = QtWidgets.QLineEdit(Dialog)
        self.masterServerEdit.setToolTip("")
        self.masterServerEdit.setObjectName("masterServerEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.masterServerEdit)
        self.ddnsKeyFilePathLabel = QtWidgets.QLabel(Dialog)
        self.ddnsKeyFilePathLabel.setObjectName("ddnsKeyFilePathLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.ddnsKeyFilePathLabel)
        self.ddnsKeyFilePathEdit = QtWidgets.QLineEdit(Dialog)
        self.ddnsKeyFilePathEdit.setObjectName("ddnsKeyFilePathEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ddnsKeyFilePathEdit)
        self.zoneTransferServerLabel = QtWidgets.QLabel(Dialog)
        self.zoneTransferServerLabel.setObjectName("zoneTransferServerLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.zoneTransferServerLabel)
        self.zoneTransferServerEdit = QtWidgets.QLineEdit(Dialog)
        self.zoneTransferServerEdit.setObjectName("zoneTransferServerEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.zoneTransferServerEdit)
        self.ip4NetworksListView = QtWidgets.QListView(Dialog)
        self.ip4NetworksListView.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ip4NetworksListView.setObjectName("ip4NetworksListView")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.ip4NetworksListView)
        self.ip4NetworksLabel = QtWidgets.QLabel(Dialog)
        self.ip4NetworksLabel.setObjectName("ip4NetworksLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.ip4NetworksLabel)
        self.ip4NetworksListView_2 = QtWidgets.QListView(Dialog)
        self.ip4NetworksListView_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ip4NetworksListView_2.setObjectName("ip4NetworksListView_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.ip4NetworksListView_2)
        self.ip6NetworksLabel = QtWidgets.QLabel(Dialog)
        self.ip6NetworksLabel.setObjectName("ip6NetworksLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.ip6NetworksLabel)
        self.ignoredZonesListView = QtWidgets.QListView(Dialog)
        self.ignoredZonesListView.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ignoredZonesListView.setObjectName("ignoredZonesListView")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.ignoredZonesListView)
        self.ignoredZonesLabel = QtWidgets.QLabel(Dialog)
        self.ignoredZonesLabel.setObjectName("ignoredZonesLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.ignoredZonesLabel)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.buttonBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(10, QtWidgets.QFormLayout.LabelRole, spacerItem)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.masterServerLabel.setText(_translate("Dialog", "Master Server"))
        self.ddnsKeyFilePathLabel.setText(_translate("Dialog", "ddns Key File"))
        self.zoneTransferServerLabel.setText(_translate("Dialog", "Server for Zone Transfer"))
        self.ip4NetworksLabel.setText(_translate("Dialog", "IPv4 networks"))
        self.ip6NetworksLabel.setText(_translate("Dialog", "IPv6 Networks"))
        self.ignoredZonesLabel.setText(_translate("Dialog", "Ignored Zones"))
